In [31]:
%pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.0.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\comp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [32]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime , timedelta

In [33]:
# 1 load dataset 
df = pd.read_csv("credit.csv")

In [34]:
# 2 check row 5 
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [35]:
# number of col and row
df.shape

(5500, 10)

In [36]:
# check columns name 
df.columns.tolist()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Type',
 'Merchant',
 'Category',
 'Amount',
 'Payment_Mode',
 'Transaction_Status',
 'Location']

In [37]:
# summary of Statistics 
df.describe(include='all')

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
count,5500.000000,5500.000000,5500,5500,5500,5500,5500.000000,5500,5500,5500
unique,NaN,NaN,230,4,7,6,NaN,4,3,4663
top,NaN,NaN,2023-01-01,Online,Uber,Groceries,NaN,PayPal,Approved,Christophermouth
freq,NaN,NaN,24,1453,833,951,NaN,1432,4698,6
mean,102749.500000,2989.954182,NaN,NaN,NaN,NaN,2492.109224,NaN,NaN,NaN
std,1587.857571,1153.928878,NaN,NaN,NaN,NaN,1444.493842,NaN,NaN,NaN
min,100000.000000,1000.000000,NaN,NaN,NaN,NaN,6.550000,NaN,NaN,NaN
25%,101374.750000,1988.000000,NaN,NaN,NaN,NaN,1236.935000,NaN,NaN,NaN
50%,102749.500000,3000.000000,NaN,NaN,NaN,NaN,2502.405000,NaN,NaN,NaN
75%,104124.250000,3990.000000,NaN,NaN,NaN,NaN,3767.957500,NaN,NaN,NaN
max,105499.000000,4998.000000,NaN,NaN,NaN,NaN,4997.490000,NaN,NaN,NaN

In [38]:
# indentify missing values 
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [39]:
# check datatype
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object

In [40]:
# convert Transaction_Date to date format
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'],errors='coerce')

In [41]:
# check datatype
df.dtypes

Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[us]
Transaction_Type                 str
Merchant                         str
Category                         str
Amount                       float64
Payment_Mode                     str
Transaction_Status               str
Location                         str
dtype: object

In [42]:
# add year , month , and day 
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

In [43]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [44]:
# check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   datetime64[us]
 3   Transaction_Type    5500 non-null   str
 4   Merchant            5500 non-null   str
 5   Category            5500 non-null   str
 6   Amount              5500 non-null   float64
 7   Payment_Mode        5500 non-null   str
 8   Transaction_Status  5500 non-null   str
 9   Location            5500 non-null   str
 10  Year                5500 non-null   int32
 11  Month               5500 non-null   int32
 12  Day                 5500 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(2), str(6)
memory usage: 494.3 KB

In [45]:
# find the Transactions january 2023 
jan_23 = df[(df['Year'] == 2023)& (df['Month']==1)]
print(jan_23.head())

   Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0          100000         4452       2023-01-01           Online  Walmart
1          100001         2775       2023-01-01              ATM  BestBuy
2          100002         2259       2023-01-01   Mobile Payment     Uber
3          100003         4545       2023-01-01           Online  BestBuy
4          100004         2137       2023-01-01              ATM   Amazon

   Category   Amount Payment_Mode Transaction_Status       Location  Year  \
0    Travel  4520.70   Debit Card           Approved      Jonesport  2023
1    Travel  1437.85   Debit Card           Approved  Port Jennifer  2023
2  Clothing  3320.52       PayPal           Approved     Port James  2023
3    Travel  2659.96   Debit Card           Approved     Hawkinston  2023
4    Travel  2517.07   Debit Card           Approved    Matthewland  2023

   Month  Day
0      1    1
1      1    1
2      1    1
3      1    1
4      1    1

In [46]:
# find the transactions with amount > 2500 transaction type = online 
online_1000 = df[(df['Amount'] > 2500) & (df['Transaction_Type']=='Online')]
# print(online_1000)

# create csv 
online_1000.to_csv('online2500.csv')

In [47]:
df['Discounted_Amount'] = df['Amount'].apply(lambda x: x * 0.95 if x > 500 else x)
print(df[['Amount', 'Discounted_Amount']].head())

    Amount  Discounted_Amount
0  4520.70          4294.6650
1  1437.85          1365.9575
2  3320.52          3154.4940
3  2659.96          2526.9620
4  2517.07          2391.2165

In [48]:
df['Amount_Category'] = pd.cut(df['Amount'], 
                               bins=[0, 100, 500, float('inf')],
                               labels=['Low', 'Medium', 'High'])
print(df[['Amount', 'Amount_Category']].head())

    Amount Amount_Category
0  4520.70            High
1  1437.85            High
2  3320.52            High
3  2659.96            High
4  2517.07            High

In [49]:
missing_merchant_percentage = df['Merchant'].isnull().mean()
if missing_merchant_percentage > 0.3:
    df.drop(columns=['Merchant'], inplace=True)
    print(f"\nMerchant column dropped due to {missing_merchant_percentage:.2%} missing values.")
else:
    print(f"\nMerchant column retained ({missing_merchant_percentage:.2%} missing values).")

Merchant column retained (0.00% missing values).

In [50]:
# total tranaction amount per category
total_amount_per_category = df.groupby('Category')['Amount'].sum().reset_index()
print(total_amount_per_category)

        Category      Amount
0       Clothing  2185530.09
1         Dining  2402259.10
2    Electronics  2319437.34
3  Entertainment  2243778.43
4      Groceries  2386772.81
5         Travel  2168822.96

In [51]:
# number of declined transactions per Payment_Mode.
declined_per_payment_mode = df[df['Transaction_Status'] == 'Declined'].groupby('Payment_Mode').size().reset_index(name='Declined_Count')
print(declined_per_payment_mode)

  Payment_Mode  Declined_Count
0  Credit Card             117
1   Debit Card             145
2       PayPal             135
3          UPI             134

In [52]:
# top 5 most frequent merchants
if 'Merchant' in df.columns:
    top_merchants = df['Merchant'].value_counts().head(5).reset_index()
    top_merchants.columns = ['Merchant', 'Transaction_Count']
    print("\nTop 5 Most Frequent Merchants:")
    print(top_merchants)
else:
    print("\nMerchant column not available for analysis.")

Top 5 Most Frequent Merchants:
  Merchant  Transaction_Count
0     Uber                833
1  Walmart                818
2  BestBuy                790
3  Netflix                774
4   Amazon                770

In [53]:
# average transaction amount per Location.
avg_amount_per_location = df.groupby('Location')['Amount'].mean().reset_index()
print(avg_amount_per_location)

          Location    Amount
0        Aaronfort  2429.860
1       Aaronmouth  2648.060
2        Aaronside   315.540
3       Abbottbury  1549.850
4      Abigailfort  3634.880
...            ...       ...
4658  Zacharyburgh  2430.690
4659  Zacharyhaven   830.360
4660  Zacharymouth  3508.690
4661   Zacharystad  2925.135
4662   Zavalaburgh   364.530

[4663 rows x 2 columns]

In [57]:
# Customers with >10 transactions in a single day
df['Date'] = df['Transaction_Date'].dt.date
transactions_per_day = df.groupby(['Customer_ID', 'Date']).size().reset_index(name='Transaction_Count')
potential_fraud_customers = transactions_per_day[transactions_per_day['Transaction_Count'] > 10]
print("Customers with >10 Transactions in a Single Day (Potential Fraud):")
print(potential_fraud_customers)

Customers with >10 Transactions in a Single Day (Potential Fraud):
Empty DataFrame
Columns: [Customer_ID, Date, Transaction_Count]
Index: []

In [59]:
# Transactions with same Customer_ID in different locations within 5 minutes
df_sorted = df.sort_values(['Customer_ID', 'Transaction_Date'])
df_sorted['Time_Diff'] = df_sorted.groupby('Customer_ID')['Transaction_Date'].diff().dt.total_seconds() / 60
df_sorted['Location_Change'] = df_sorted.groupby('Customer_ID')['Location'].shift() != df_sorted['Location']
same_customer_diff_location = df_sorted[(df_sorted['Time_Diff'].notnull()) & (df_sorted['Time_Diff'] <= 5) & (df_sorted['Location_Change'])]
print("Transactions with Same Customer_ID in Different Locations within 5 Minutes:")
print(same_customer_diff_location[['Customer_ID', 'Transaction_Date', 'Location', 'Time_Diff']])

Transactions with Same Customer_ID in Different Locations within 5 Minutes:
      Customer_ID Transaction_Date           Location  Time_Diff
3717         1079       2023-06-04         Davidville        0.0
5461         1140       2023-08-16  South Lorichester        0.0
5468         1343       2023-08-16  Lake Danielleview        0.0
4582         1709       2023-07-10        West Rhonda        0.0
2588         1776       2023-04-18    New Jeffreyside        0.0
207          1910       2023-01-09   Port Michaelfurt        0.0
2637         1956       2023-04-20          Crossstad        0.0
4559         2122       2023-07-09       Sarahborough        0.0
1432         2136       2023-03-01        South Aaron        0.0
4569         2165       2023-07-10         Grantville        0.0
3465         2270       2023-05-25   West Kristenview        0.0
767          2884       2023-02-01      Alexandrabury        0.0
2507         3131       2023-04-15        Matthewfurt        0.0
2699         3234       2023-04-23   Christophershire        0.0
4941         3351       2023-07-25         East Carol        0.0
1841         3783       2023-03-18  North Michelleton        0.0
3511         3861       2023-05-27          Kingburgh        0.0
1960         4143       2023-03-23          Singhfort        0.0
1047         4238       2023-02-13      South Rebecca        0.0
3282         4429       2023-05-17       Santanamouth        0.0
5373         4916       2023-08-12          New James        0.0

In [58]:
# High-risk transactions (Amount > $5000 and Online)
high_risk_transactions = df[(df['Amount'] > 5000) & (df['Transaction_Type'] == 'Online')]
print("High-Risk Transactions (Amount > $5000 and Online):")
print(high_risk_transactions)

High-Risk Transactions (Amount > $5000 and Online):
Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Transaction_Date, Transaction_Type, Merchant, Category, Amount, Payment_Mode, Transaction_Status, Location, Year, Month, Day, Discounted_Amount, Amount_Category, Date]
Index: []